<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNiceXtJ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNiceXtJ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNiceXtJ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNiceXtJ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerNiceXtJ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'NiceXtJ',
    'container.build_id' => '980ba401',
    'container.build_time' => 1581618114,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNiceXtJ');
